Repository aeye-lab/pymovements, pull requests merged in 2023-01, with the labels that each got.

#87 Add multi-channel support for synthetic.step_function
  src/pymovements/synthetic/step_function.py
  tests/synthetic/test_step_function.py
Labels: enhancement

#89 fix some linting and code style issues
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  pylintrc
  src/pymovements/base.py
  src/pymovements/plot.py
  src/pymovements/synthetic/step_function.py
  tests/events/test_events_base.py
  tests/synthetic/test_step_function.py
  tests/test_transformations.py
Labels: enhancement

#88 Add utils for downloading and extracting archives
  setup.cfg
  src/pymovements/utils/archives.py
  src/pymovements/utils/downloads.py
Labels: enhancement

#90 Utils: fix bug in get_filepaths()
  src/pymovements/utils/paths.py
Labels: bug

#92 Docs/logo
  README.md
  docs/source/_static/logo.svg
Labels: documentation
