Repository aeye-lab/pymovements, pull requests merged in 2023-11, with the labels that each got.

#608 docs: add git alias hint for creating new branches
  CONTRIBUTING.md
Labels: documentation

#592 feat: gaze_dataframe.unnest() supports multi-col unnest
  src/pymovements/dataset/dataset_files.py
  src/pymovements/gaze/gaze_dataframe.py
  tests/unit/gaze/gaze_dataframe_unnest_test.py
Labels: enhancement

#619 feat: add new dataset GazeGraph
  docs/source/bibliography.bib
  src/pymovements/datasets/__init__.py
  src/pymovements/datasets/gaze_graph.py
  tests/files/gazegraph_example.csv
  tests/functional/dataset_processing_test.py
Labels: enhancement

#590 feat: Add gaze.from_asc()
  src/pymovements/gaze/__init__.py
  src/pymovements/gaze/io.py
  src/pymovements/utils/parsing.py
  tests/files/eyelink_monocular_example.asc
  tests/functional/gaze_file_processing_test.py
  tests/unit/gaze/io/asc_test.py
Labels: enhancement

#615 test: Test for warning when distance column and distance_cm specified
  pyproject.toml
  tests/unit/gaze/gaze_transform_test.py
Labels: internal

#594 docs: Add missing column argument docs and note on csv column dtypes
  src/pymovements/dataset/dataset_definition.py
  src/pymovements/gaze/gaze_dataframe.py
  src/pymovements/gaze/io.py
Labels: documentation

#632 ci: add construction worker emojis to release draft
  .github/release-drafter.yml
Labels: internal

#625 ci: don't fail pytest on incomplete coverage
  tox.ini
Labels: internal

#624 build: raise minor version on breaking changes only
  .github/release-drafter.yml
Labels: build
