Repository aeye-lab/pymovements, pull requests merged in 2023-10, with the labels that each got.

#603 ci: add github workflow for autolabeler
  .github/release-drafter.yml
  .github/workflows/autolabeler.yml
Labels: internal

#605 ci: don't setup python twice in github workflow
  .github/workflows/tests.yml
Labels: internal

#604 ci: add publish github workflow
  .github/workflows/publish.yml
  tox.ini
Labels: internal

#602 ci: treat warnings as errors
  pyproject.toml
Labels: internal

#579 feat: Optionally remove single-child top-level directory from extracted archives
  src/pymovements/dataset/dataset.py
  src/pymovements/dataset/dataset_download.py
  src/pymovements/utils/archives.py
  src/pymovements/utils/downloads.py
  tests/unit/dataset/dataset_download_test.py
  tests/unit/utils/archives_test.py
  tests/unit/utils/downloads_test.py
Labels: enhancement

#612 chore: migrate deprecated polars funtions
  pyproject.toml
  src/pymovements/events/processing.py
  src/pymovements/gaze/gaze_dataframe.py
  src/pymovements/gaze/transforms.py
Labels: enhancement

#614 fix: SchemaFieldNotFoundError When Loading Preprocessed Data
  src/pymovements/dataset/dataset_files.py
  tests/functional/dataset_processing_test.py
Labels: fix
