Repository aeye-lab/pymovements, pull requests merged in 2023-12, with the labels that each got.

#636 feat: add PoTeC dataset
  docs/source/bibliography.bib
  src/pymovements/dataset/dataset_files.py
  src/pymovements/datasets/__init__.py
  src/pymovements/datasets/potec.py
  tests/files/potec_example.tsv
  tests/functional/dataset_processing_test.py
  tests/functional/gaze_file_processing_test.py
  tests/unit/datasets/datasets_test.py
  tests/unit/datasets/potec_test.py
Labels: enhancement

#639 docs: include teaser in readme
  README.md
Labels: documentation

#645 test: fix expected values in parsing
  tests/unit/gaze/io/asc_test.py
  tests/unit/utils/parsing_test.py
Labels: internal
