Repository aeye-lab/pymovements, pull requests merged in 2024-09, with the labels that each got.

#778 fix sb sat wrong experiment config
  src/pymovements/datasets/sb_sat.py
Labels: fix

#792 docs: docstring of traceplot had wrong pad_value default
  src/pymovements/plotting/traceplot.py
Labels: documentation

#795 refactor public dataset tests into 'gaze' and 'precomputed_events'
  tests/unit/datasets/datasets_test.py
Labels: internal

#784 Event aoi mapping
  src/pymovements/datasets/toy_dataset.py
  src/pymovements/events/frame.py
  src/pymovements/gaze/gaze_dataframe.py
  src/pymovements/utils/__init__.py
  src/pymovements/utils/aois.py
  tests/unit/events/event_aoi_mapping_test.py
Labels: enhancement

#811 fix stimulus text wrong handling of missing values
  src/pymovements/stimulus/text.py
  tests/unit/events/event_aoi_mapping_test.py
  tests/unit/stimulus/text_test.py
Labels: fix

#838 docs: update docstring of utils downloads
  src/pymovements/utils/downloads.py
Labels: documentation

#821 docs: update docstring of copco dataset definition
  src/pymovements/datasets/copco.py
Labels: documentation

#820 docs: update docstring of dataset definition
  src/pymovements/dataset/dataset_definition.py
Labels: documentation

#824 docs: update docstring of fakenews dataset definition
  src/pymovements/datasets/fakenews.py
Labels: documentation

#837 docs: update docstring of gaze screen
  src/pymovements/gaze/screen.py
Labels: documentation

#836 docs: update docstring of gaze experiment
  src/pymovements/gaze/experiment.py
Labels: documentation

#835 docs: update docstring of events processing
  src/pymovements/events/processing.py
Labels: documentation

#834 docs: update docstring of toy_dataset_eyelink dataset definition
  src/pymovements/datasets/toy_dataset_eyelink.py
Labels: documentation

#833 docs: update docstring of toy_dataset dataset definition
  src/pymovements/datasets/toy_dataset.py
Labels: documentation

#832 docs: update docstring of sb_sat dataset definition
  src/pymovements/datasets/sb_sat.py
Labels: documentation

#831 docs: update docstring of potec dataset definition
  src/pymovements/datasets/potec.py
Labels: documentation

#830 docs: update docstring of judo1000 dataset definition
  src/pymovements/datasets/judo1000.py
Labels: documentation

#829 docs: update docstring of hbn dataset definition
  src/pymovements/datasets/hbn.py
Labels: documentation

#828 docs: update docstring of gazebasevr dataset definition
  src/pymovements/datasets/gazebasevr.py
Labels: documentation

#827 docs: update docstring of gazebase dataset definition
  src/pymovements/datasets/gazebase.py
Labels: documentation

#826 docs: update docstring of gazes_on_faces dataset definition
  src/pymovements/datasets/gaze_on_faces.py
Labels: documentation

#825 docs: update docstring of gaze_graph dataset definition
  src/pymovements/datasets/gaze_graph.py
Labels: documentation

#823 docs: update docstring of emtec dataset definition
  src/pymovements/datasets/emtec.py
Labels: documentation

#822 docs: update docstring of didec dataset definition
  src/pymovements/dataset/.dataset_definition.py.swp
  src/pymovements/datasets/didec.py
Labels: documentation

#818 ci: manually update pre-commit config
  .pre-commit-config.yaml
Labels: internal

#819 ci: update pydoclint in pre-commit config
  .pre-commit-config.yaml
  src/pymovements/datasets/gaze_graph.py
Labels: internal

#767 feat!: Custom patterns for parsing logged metadata in ASC files
  src/pymovements/dataset/dataset_files.py
  src/pymovements/gaze/io.py
  src/pymovements/utils/parsing.py
  tests/functional/gaze_file_processing_test.py
  tests/unit/gaze/io/asc_test.py
  tests/unit/utils/parsing_test.py
Labels: enhancement, breaking
