Repository aeye-lab/pymovements, pull requests merged in 2024-03, with the labels that each got.

#660 build: add support for python 3.12
  .github/workflows/tests.yml
  docs/source/conf.py
  pyproject.toml
  src/pymovements/utils/archives.py
  tox.ini
Labels: build

#676 feat: add text stimulus class
  src/pymovements/__init__.py
  src/pymovements/stimulus/__init__.py
  src/pymovements/stimulus/text.py
  tests/files/toy_text_1_1_aoi.csv
  tests/unit/stimulus/text_test.py
Labels: enhancement

#702 feat: parse eyelink metadata
  CONTRIBUTING.md
  src/pymovements/utils/parsing.py
  tests/unit/utils/parsing_test.py
Labels: enhancement

#709 ci: disable too-many-instance-attributes in pylint
  pylintrc
Labels: internal

#698 refactor: use gaze.io for loading dataset files
  src/pymovements/dataset/dataset_files.py
  src/pymovements/gaze/gaze_dataframe.py
  src/pymovements/gaze/io.py
  tests/unit/dataset/dataset_files_test.py
  tests/unit/dataset/dataset_test.py
  tests/unit/gaze/io/ipc_test.py
Labels: internal

#643 feat: timestamp unit specification
  docs/source/tutorials/local-dataset.ipynb
  src/pymovements/dataset/dataset_definition.py
  src/pymovements/dataset/dataset_files.py
  src/pymovements/datasets/gaze_graph.py
  src/pymovements/datasets/gaze_on_faces.py
  src/pymovements/datasets/gazebase.py
  src/pymovements/datasets/gazebasevr.py
  src/pymovements/datasets/hbn.py
  src/pymovements/datasets/judo1000.py
  src/pymovements/datasets/potec.py
  src/pymovements/datasets/sb_sat.py
  src/pymovements/datasets/toy_dataset.py
  src/pymovements/datasets/toy_dataset_eyelink.py
  src/pymovements/gaze/gaze_dataframe.py
  src/pymovements/gaze/integration.py
  src/pymovements/gaze/io.py
  tests/functional/dataset_processing_test.py
  tests/functional/gaze_file_processing_test.py
  tests/unit/dataset/dataset_test.py
  tests/unit/gaze/gaze_dataframe_unnest_test.py
  tests/unit/gaze/gaze_init_test.py
  tests/unit/gaze/gaze_transform_test.py
  tests/unit/gaze/integration_numpy_test.py
  tests/unit/gaze/io/csv_test.py
Labels: enhancement

#700 feat: add clip transformation
  src/pymovements/dataset/dataset.py
  src/pymovements/gaze/gaze_dataframe.py
  src/pymovements/gaze/transforms.py
  tests/unit/dataset/dataset_test.py
  tests/unit/gaze/gaze_transform_test.py
Labels: enhancement

#710 fix!: correct pixel origin string to upper left instead of lower left
  docs/source/tutorials/local-dataset.ipynb
  src/pymovements/dataset/dataset.py
  src/pymovements/datasets/gazebase.py
  src/pymovements/datasets/judo1000.py
  src/pymovements/datasets/potec.py
  src/pymovements/datasets/toy_dataset.py
  src/pymovements/datasets/toy_dataset_eyelink.py
  src/pymovements/gaze/experiment.py
  src/pymovements/gaze/gaze_dataframe.py
  src/pymovements/gaze/screen.py
  src/pymovements/gaze/transforms.py
  src/pymovements/gaze/transforms_numpy.py
  tests/unit/dataset/dataset_test.py
  tests/unit/gaze/gaze_transform_test.py
  tests/unit/gaze/integration_numpy_test.py
  tests/unit/gaze/integration_pandas_test.py
  tests/unit/gaze/screen_test.py
  tests/unit/gaze/transforms/center_origin_test.py
  tests/unit/gaze/transforms/deg2pix_test.py
  tests/unit/gaze/transforms/pix2deg_test.py
  tests/unit/gaze/transforms_numpy_test.py
  tests/unit/plotting/traceplot_test.py
  tests/unit/plotting/tsplot_test.py
Labels: fix, breaking

#673 feat: introduce measure_samples(), MeasureLibrary and null_ratio
  src/pymovements/__init__.py
  src/pymovements/gaze/gaze_dataframe.py
  src/pymovements/measure/__init__.py
  src/pymovements/measure/library.py
  src/pymovements/measure/measures.py
  tests/unit/dataset/dataset_files_test.py
  tests/unit/gaze/measure_test.py
  tests/unit/measure/measure_library_test.py
  tests/unit/measure/null_ratio_test.py
Labels: enhancement

#711 fix: forward experiment from dataset definition to from_asc
  src/pymovements/dataset/dataset_files.py
  tests/unit/dataset/dataset_files_test.py
Labels: fix
