Repository aeye-lab/pymovements, pull requests merged in 2024-02, with the labels that each got.

#656 fix: don't fail in event fill if event onsets/offsets not within timesteps
  src/pymovements/events/detection/_fill.py
  tests/unit/gaze/detect_test.py
Labels: fix

#670 feat: add trial_columns to EventDataFrame
  src/pymovements/events/frame.py
  tests/unit/events/frame_test.py
Labels: enhancement

#671 feat: add EventDataFrame.add_trial_column()
  src/pymovements/events/frame.py
  tests/unit/events/frame_test.py
Labels: enhancement

#617 feat: add EyeTracker class
  src/pymovements/datasets/toy_dataset_eyelink.py
  src/pymovements/gaze/experiment.py
  src/pymovements/gaze/eyetracker.py
  src/pymovements/plotting/heatmap.py
  tests/unit/gaze/experiment_test.py
  tests/unit/gaze/eyetracker_test.py
Labels: enhancement

#684 docs: update contributing.md for new tox command
  CONTRIBUTING.md
Labels: documentation

#682 build: add typing_extensions to be able to install pymovements from source
  pyproject.toml
Labels: build

#630 docs: add 'Integration and IO' rubric to api reference docs
  src/pymovements/gaze/__init__.py
Labels: documentation

#693 ci: improve tox integration command
  tox.ini
Labels: internal

#685 ci: update github action versions
  .github/workflows/tests.yml
Labels: internal

#691 fix: update checksum of PoTeC resource file
  docs/source/bibliography.bib
  src/pymovements/datasets/gaze_graph.py
  src/pymovements/datasets/gaze_on_faces.py
  src/pymovements/datasets/gazebase.py
  src/pymovements/datasets/gazebasevr.py
  src/pymovements/datasets/hbn.py
  src/pymovements/datasets/judo1000.py
  src/pymovements/datasets/potec.py
  src/pymovements/datasets/sb_sat.py
  src/pymovements/datasets/toy_dataset.py
  src/pymovements/datasets/toy_dataset_eyelink.py
Labels: fix
