Repository aeye-lab/pymovements, pull requests merged in 2024-10, with the labels that each got.

#846 build: upgrade pyarrow
  pyproject.toml
Labels: build

#848 feat: adjust aoi mapping to aoi dataframe columns
  src/pymovements/utils/aois.py
Labels: enhancement

#851 feat: aoi mapping extended to end coordinate instead of width/height
  src/pymovements/stimulus/text.py
  src/pymovements/utils/aois.py
  tests/files/toy_text_1_1_aoi.csv
  tests/unit/events/event_aoi_mapping_test.py
  tests/unit/gaze/gaze_aoi_mapping_test.py
  tests/unit/stimulus/text_test.py
Labels: enhancement

#855 fix: correct trial columns in SB-SAT dataset
  src/pymovements/datasets/sb_sat.py
  tests/functional/gaze_file_processing_test.py
Labels: fix

#866 docs: Add missing modules to documentation
  docs/source/reference/index.rst
Labels: documentation

#876 fix: correctly add EyeTracker class to gaze module
  src/pymovements/gaze/__init__.py
Labels: documentation

#858 feat: add support for .ias files in stimulus.text.from_file()
  src/pymovements/stimulus/text.py
  tests/unit/stimulus/text_test.py
Labels: enhancement

#857 dataset: beijing sentence corpus
  docs/source/bibliography.bib
  src/pymovements/datasets/__init__.py
  src/pymovements/datasets/bsc.py
  tests/unit/datasets/datasets_test.py
Labels: dataset

#862 dataset: add InteRead dataset
  docs/source/bibliography.bib
  src/pymovements/datasets/__init__.py
  src/pymovements/datasets/interead.py
  tests/unit/datasets/datasets_test.py
Labels: dataset

#863 fix: copy event resource files instead of moving them to events directory
  src/pymovements/dataset/dataset_download.py
  tests/unit/dataset/dataset_download_test.py
Labels: bug, fix

#873 hotfix: CopCo dataset precomputed events loading
  src/pymovements/datasets/copco.py
Labels: bug

#882 ci: ignore too-many-public-methods
  pylintrc
Labels: internal
