Repository aeye-lab/pymovements, pull requests merged in 2025-04, with the labels that each got.

#1077 chore: remove unnecessary ignore of cyclic-import
  src/pymovements/gaze/io.py
Labels: internal

#887 feat: add support for multiple recording specs per file to gaze.from_asc()
  src/pymovements/gaze/_utils/parsing.py
  src/pymovements/gaze/io.py
  tests/unit/gaze/_utils/_parsing_test.py
Labels: enhancement, parsing

#1076 feat: add auto_column_detect to from_csv()
  pylintrc
  src/pymovements/dataset/dataset_files.py
  src/pymovements/gaze/gaze_dataframe.py
  src/pymovements/gaze/io.py
  tests/unit/gaze/io/csv_test.py
Labels: enhancement

#1080 depr: deprecate `utils.aois` in favor of `TextStimulus.get_aoi()`
  src/pymovements/events/frame.py
  src/pymovements/gaze/gaze_dataframe.py
  src/pymovements/stimulus/text.py
  src/pymovements/utils/aois.py
  tests/unit/events/event_aoi_mapping_test.py
  tests/unit/stimulus/text_test.py
  tests/unit/utils/aois_test.py
Labels: deprecation

#1084 feat: use locale encoding by default in from_asc()
  src/pymovements/datasets/toy_dataset_eyelink.py
  src/pymovements/datasets/toy_dataset_eyelink.yaml
  src/pymovements/gaze/_utils/parsing.py
  src/pymovements/gaze/io.py
  tests/files/eyelink_monocular_no_dummy_example.asc
  tests/unit/gaze/io/asc_test.py
Labels: enhancement

#1085 chore: refactor filling experiment in from_asc()
  src/pymovements/gaze/io.py
  tests/unit/gaze/io/asc_test.py
Labels: internal

#1093 chore: add context section to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: internal

#1107 fix: Remove bullet point from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: fix

#1101 test: correct time and velocity in detect_test
  tests/unit/gaze/detect_test.py
Labels: internal

#1106 fix: Use GAZE_COORDS message to determine screen resolution
  src/pymovements/gaze/_utils/parsing.py
  src/pymovements/gaze/io.py
  tests/unit/gaze/_utils/_parsing_test.py
  tests/unit/gaze/io/asc_test.py
Labels: fix

#1088 feat: add `DatasetDefinition.to_dict()`
  src/pymovements/dataset/_utils/_yaml.py
  src/pymovements/dataset/dataset_definition.py
  tests/unit/dataset/dataset_definition_test.py
  tests/unit/datasets/datasets_test.py
Labels: enhancement

#922 feat: add `GazeDataFrame.compute_event_properties()`
  src/pymovements/dataset/dataset.py
  src/pymovements/gaze/gaze_dataframe.py
  tests/unit/gaze/gaze_dataframe_test.py
Labels: enhancement

#1046 feat: raise helpful error message for existing event properties
  src/pymovements/dataset/dataset.py
  src/pymovements/events/processing.py
  src/pymovements/gaze/gaze_dataframe.py
  tests/unit/dataset/dataset_test.py
  tests/unit/events/processing_test.py
Labels: enhancement

#1096 feat: add `DatasetDefinition.long_name`
  src/pymovements/dataset/dataset_definition.py
  src/pymovements/datasets/bsc.py
  src/pymovements/datasets/bsc.yaml
  src/pymovements/datasets/bsc2.py
  src/pymovements/datasets/bsc2.yaml
  src/pymovements/datasets/codecomprehension.py
  src/pymovements/datasets/codecomprehension.yaml
  src/pymovements/datasets/copco.py
  src/pymovements/datasets/copco.yaml
  src/pymovements/datasets/daemons.py
  src/pymovements/datasets/daemons.yaml
  src/pymovements/datasets/didec.py
  src/pymovements/datasets/didec.yaml
  src/pymovements/datasets/emtec.py
  src/pymovements/datasets/emtec.yaml
  src/pymovements/datasets/fakenews.py
  src/pymovements/datasets/fakenews.yaml
  src/pymovements/datasets/gaze_graph.py
  src/pymovements/datasets/gaze_graph.yaml
  src/pymovements/datasets/gaze_on_faces.py
  src/pymovements/datasets/gaze_on_faces.yaml
  src/pymovements/datasets/gazebase.py
  src/pymovements/datasets/gazebase.yaml
  src/pymovements/datasets/gazebasevr.py
  src/pymovements/datasets/gazebasevr.yaml
  src/pymovements/datasets/hbn.py
  src/pymovements/datasets/hbn.yaml
  src/pymovements/datasets/interead.py
  src/pymovements/datasets/interead.yaml
  src/pymovements/datasets/judo1000.py
  src/pymovements/datasets/judo1000.yaml
  src/pymovements/datasets/mousecursor.py
  src/pymovements/datasets/mousecursor.yaml
  src/pymovements/datasets/potec.py
  src/pymovements/datasets/potec.yaml
  src/pymovements/datasets/potsdam_binge_remote_pvt.py
  src/pymovements/datasets/potsdam_binge_remote_pvt.yaml
  src/pymovements/datasets/potsdam_binge_wearable_pvt.py
  src/pymovements/datasets/potsdam_binge_wearable_pvt.yaml
  src/pymovements/datasets/provo.py
  src/pymovements/datasets/provo.yaml
  src/pymovements/datasets/sb_sat.py
  src/pymovements/datasets/sb_sat.yaml
  src/pymovements/datasets/toy_dataset.py
  src/pymovements/datasets/toy_dataset.yaml
  src/pymovements/datasets/toy_dataset_eyelink.py
  src/pymovements/datasets/toy_dataset_eyelink.yaml
  src/pymovements/datasets/ucl.py
  src/pymovements/datasets/ucl.yaml
  tests/unit/dataset/dataset_definition_test.py
Labels: enhancement

#1097 feat: print disclaimer when downloading a public dataset
  src/pymovements/dataset/dataset_download.py
Labels: enhancement, highlight

#1114 ci: set fail-fast to false in integration tests
  .github/workflows/datasets.yml
Labels: internal

#1059 chore: remove mirrors from datasets with no real mirrors
  src/pymovements/datasets/bsc.py
  src/pymovements/datasets/bsc.yaml
  src/pymovements/datasets/bsc2.py
  src/pymovements/datasets/bsc2.yaml
  src/pymovements/datasets/codecomprehension.py
  src/pymovements/datasets/codecomprehension.yaml
  src/pymovements/datasets/copco.py
  src/pymovements/datasets/copco.yaml
  src/pymovements/datasets/daemons.py
  src/pymovements/datasets/daemons.yaml
  src/pymovements/datasets/didec.py
  src/pymovements/datasets/didec.yaml
  src/pymovements/datasets/emtec.py
  src/pymovements/datasets/emtec.yaml
  src/pymovements/datasets/fakenews.py
  src/pymovements/datasets/fakenews.yaml
  src/pymovements/datasets/gaze_graph.py
  src/pymovements/datasets/gaze_graph.yaml
  src/pymovements/datasets/gaze_on_faces.py
  src/pymovements/datasets/gaze_on_faces.yaml
  src/pymovements/datasets/gazebase.py
  src/pymovements/datasets/gazebase.yaml
  src/pymovements/datasets/gazebasevr.py
  src/pymovements/datasets/gazebasevr.yaml
  src/pymovements/datasets/hbn.py
  src/pymovements/datasets/hbn.yaml
  src/pymovements/datasets/interead.py
  src/pymovements/datasets/interead.yaml
  src/pymovements/datasets/judo1000.py
  src/pymovements/datasets/judo1000.yaml
  src/pymovements/datasets/mousecursor.py
  src/pymovements/datasets/mousecursor.yaml
  src/pymovements/datasets/potec.py
  src/pymovements/datasets/potec.yaml
  src/pymovements/datasets/provo.py
  src/pymovements/datasets/provo.yaml
  src/pymovements/datasets/sb_sat.py
  src/pymovements/datasets/sb_sat.yaml
  src/pymovements/datasets/toy_dataset.py
  src/pymovements/datasets/toy_dataset.yaml
  src/pymovements/datasets/toy_dataset_eyelink.py
  src/pymovements/datasets/toy_dataset_eyelink.yaml
  src/pymovements/datasets/ucl.py
  src/pymovements/datasets/ucl.yaml
Labels: internal

#1121 feat: make `DatasetDefinition.long_name` optional
  src/pymovements/dataset/dataset.py
  src/pymovements/dataset/dataset_definition.py
  src/pymovements/dataset/dataset_download.py
  tests/unit/dataset/dataset_definition_test.py
Labels: enhancement

#1092 chore: set `patterns` default to `None` in `from_asc()`
  src/pymovements/gaze/io.py
Labels: internal

#1123 ci: reduce CI compute by canceling outdated runs in PRs
  .github/workflows/tests.yml
Labels: internal

#1004 feat: support passing `DatasetDefinition` to gaze init and io
  src/pymovements/dataset/dataset_files.py
  src/pymovements/gaze/gaze_dataframe.py
  src/pymovements/gaze/io.py
  tests/functional/gaze_file_processing_test.py
  tests/unit/dataset/dataset_files_test.py
  tests/unit/gaze/gaze_init_test.py
  tests/unit/gaze/io/asc_test.py
  tests/unit/gaze/io/csv_test.py
Labels: enhancement

#1122 dataset: add EMTeC reading measures
  src/pymovements/datasets/emtec.py
  src/pymovements/datasets/emtec.yaml
Labels: dataset

#1087 ci: create workflow for benchmarking import times
  .github/workflows/benchmark.yml
  pyproject.toml
  tests/benchmark/import_test.py
  tox.ini
Labels: internal

#1104 dataset: add PoTeC fixation resources
  src/pymovements/datasets/potec.py
  src/pymovements/datasets/potec.yaml
Labels: dataset

#1081 depr: deprecate `utils.plotting`
  src/pymovements/plotting/_matplotlib.py
  src/pymovements/plotting/heatmap.py
  src/pymovements/plotting/scanpathplot.py
  src/pymovements/plotting/traceplot.py
  src/pymovements/stimulus/image.py
  src/pymovements/utils/__init__.py
  src/pymovements/utils/plotting.py
  tests/unit/stimulus/image_plotting_test.py
  tests/unit/utils/plotting_test.py
Labels: deprecation
