Repository aeye-lab/pymovements, pull requests merged in 2025-05, with the labels that each got.

#1108 feat: implement `Experiment.from_dict()`
  src/pymovements/gaze/experiment.py
  tests/unit/gaze/experiment_test.py
Labels: enhancement

#1140 chore: reuse `Experiment.from_dict()` in `DatasetDefinition.from_yaml()`
  src/pymovements/dataset/dataset_definition.py
Labels: internal

#1112 feat: HTML representations for Jupyter notebooks
  .pre-commit-config.yaml
  src/pymovements/_utils/_html.py
  src/pymovements/dataset/dataset.py
  src/pymovements/dataset/dataset_definition.py
  src/pymovements/dataset/dataset_paths.py
  src/pymovements/events/frame.py
  src/pymovements/events/precomputed.py
  src/pymovements/gaze/experiment.py
  src/pymovements/gaze/eyetracker.py
  src/pymovements/gaze/gaze_dataframe.py
  src/pymovements/gaze/screen.py
  src/pymovements/stimulus/image.py
  src/pymovements/stimulus/text.py
  tests/unit/_utils/_html_test.py
Labels: enhancement

#1149 feat: add `exclude_none` argument to `to_dict()` methods
  src/pymovements/dataset/dataset_definition.py
  src/pymovements/gaze/experiment.py
  src/pymovements/gaze/eyetracker.py
  src/pymovements/gaze/screen.py
  tests/unit/dataset/dataset_definition_test.py
  tests/unit/gaze/experiment_test.py
  tests/unit/gaze/eyetracker_test.py
  tests/unit/gaze/screen_test.py
Labels: enhancement

#1150 chore!: restrict boolean arguments in `to_dict()` to keyword-only
  src/pymovements/dataset/dataset_definition.py
  src/pymovements/gaze/experiment.py
  src/pymovements/gaze/eyetracker.py
  src/pymovements/gaze/screen.py
Labels: internal, breaking

#1151 fix: don't share experiment instance between loaded files
  src/pymovements/dataset/dataset_files.py
  tests/unit/dataset/dataset_test.py
Labels: fix

#1153 chore: set `DatasetDefinition.time_unit` default to `None`
  src/pymovements/dataset/dataset_definition.py
  tests/unit/dataset/dataset_definition_test.py
Labels: internal

#1064 feat: add dynamic `has_resources` property to `DatasetDefinition`
  src/pymovements/dataset/_utils/_resources.py
  src/pymovements/dataset/dataset_definition.py
  tests/integration/public_dataset_processing_test.py
  tests/unit/dataset/dataset_definition_test.py
Labels: enhancement

#1102 dataset: add CoLAGaze dataset
  docs/source/bibliography.bib
  docs/source/datasets/public_datasets.csv
  src/pymovements/datasets/__init__.py
  src/pymovements/datasets/colagaze.py
  src/pymovements/datasets/colagaze.yaml
  src/pymovements/datasets/datasets.yaml
  tests/unit/datasets/datasets_test.py
Labels: dataset

#1089 feat: automatically infer if resources need extract
  src/pymovements/dataset/_utils/_archives.py
  src/pymovements/dataset/_utils/_downloads.py
  src/pymovements/dataset/dataset.py
  src/pymovements/dataset/dataset_download.py
  src/pymovements/exceptions.py
  src/pymovements/utils/downloads.py
  tests/unit/dataset/_utils/_archives_test.py
  tests/unit/dataset/_utils/_downloads_test.py
  tests/unit/dataset/dataset_download_test.py
  tests/unit/utils/downloads_test.py
Labels: enhancement

#1165 docs: Change `five_point` to `fivepoint`
  src/pymovements/gaze/transforms.py
  tests/unit/gaze/gaze_transform_test.py
Labels: documentation

#1145 ci: add local pre-commit hook to write datasets.yaml
  .pre-commit-config.yaml
  src/pymovements/_scripts/__init__.py
  src/pymovements/_scripts/write_datasets_yaml.py
  tests/unit/_scripts/write_datasets_yaml_test.py
Labels: internal

#1173 docs: update discord link
  README.md
Labels: documentation

#1168 ci: reduce number of caches on github
  .github/workflows/benchmark.yml
  .github/workflows/datasets.yml
  .github/workflows/tests.yml
Labels: internal
