Repository aeye-lab/pymovements, pull requests merged in 2025-10, with the labels that each got.

#1288 feat!: add `as_dict` argument to `split()` methods
  src/pymovements/dataset/dataset.py
  src/pymovements/events/events.py
  src/pymovements/gaze/gaze.py
  tests/unit/events/events_test.py
  tests/unit/gaze/gaze_test.py
Labels: enhancement, breaking

#1221 docs: upgrade `Gaze.split()` documentation
  src/pymovements/gaze/gaze.py
Labels: documentation

#1294 feat: add `load_kwargs` to `ResourceDefinition`
  src/pymovements/dataset/dataset_files.py
  src/pymovements/dataset/resources.py
  tests/unit/dataset/dataset_files_test.py
  tests/unit/dataset/dataset_test.py
  tests/unit/dataset/resources_test.py
Labels: enhancement

#1302 ci: update CODEOWNERS
  .github/CODEOWNERS
Labels: internal

#1306 ci: exclude pre-commit-ci bot in release-drafter
  .github/release-drafter.yml
Labels: internal

#1307 ci: revert removing exclude of bot contributors
  .github/release-drafter.yml
Labels: internal
