Repository aeye-lab/pymovements, pull requests merged in 2025-03, with the labels that each got.

#983 docs: Fix typo in local-dataset.ipynb
  docs/source/tutorials/local-dataset.ipynb
Labels: documentation

#986 docs: fix warnings in sphinx documentation build
  docs/source/_templates/class.rst
  docs/source/conf.py
  src/pymovements/dataset/__init__.py
  src/pymovements/dataset/dataset.py
  src/pymovements/dataset/dataset_definition.py
  src/pymovements/dataset/dataset_library.py
  src/pymovements/dataset/dataset_paths.py
  src/pymovements/datasets/__init__.py
  src/pymovements/datasets/bsc.py
  src/pymovements/datasets/bsc2.py
  src/pymovements/datasets/codecomprehension.py
  src/pymovements/datasets/copco.py
  src/pymovements/datasets/daemons.py
  src/pymovements/datasets/didec.py
  src/pymovements/datasets/emtec.py
  src/pymovements/datasets/gaze_graph.py
  src/pymovements/datasets/gaze_on_faces.py
  src/pymovements/datasets/gazebase.py
  src/pymovements/datasets/gazebasevr.py
  src/pymovements/datasets/hbn.py
  src/pymovements/datasets/interead.py
  src/pymovements/datasets/judo1000.py
  src/pymovements/datasets/potec.py
  src/pymovements/datasets/provo.py
  src/pymovements/datasets/sb_sat.py
  src/pymovements/datasets/toy_dataset.py
  src/pymovements/datasets/toy_dataset_eyelink.py
  src/pymovements/datasets/ucl.py
  src/pymovements/events/__init__.py
  src/pymovements/events/processing.py
  src/pymovements/gaze/__init__.py
  src/pymovements/gaze/gaze_dataframe.py
  src/pymovements/gaze/integration.py
  src/pymovements/gaze/io.py
  src/pymovements/measure/__init__.py
  src/pymovements/plotting/__init__.py
  src/pymovements/reading_measures/__init__.py
  src/pymovements/stimulus/__init__.py
  src/pymovements/synthetic/__init__.py
  src/pymovements/utils/__init__.py
Labels: documentation

#985 docs: add Datasets tab to main page in documentation
  docs/source/bibliography.bib
  docs/source/datasets/example_datasets.csv
  docs/source/datasets/index.rst
  docs/source/datasets/public_datasets.csv
  docs/source/index.rst
  src/pymovements/datasets/daemons.py
  src/pymovements/datasets/potec.py
Labels: documentation

#988 ci: add spearate documentation section in release drafter
  .github/release-drafter.yml
Labels: internal

#886 docs: Add release guide to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#976 depr: Deprecate `utils.parsing` in favor of `gaze.from_asc()`
  pyproject.toml
  src/pymovements/gaze/_utils/__init__.py
  src/pymovements/gaze/_utils/parsing.py
  src/pymovements/gaze/io.py
  src/pymovements/utils/parsing.py
  tests/unit/gaze/_utils/_parsing_test.py
  tests/unit/utils/parsing_test.py
Labels: urgent, deprecation

#994 ci: use correct documentation label in release drafter
  .github/release-drafter.yml
Labels: internal

#852 feat: entire row of aoi dataframe instead of just ia string
  src/pymovements/events/frame.py
  src/pymovements/gaze/gaze_dataframe.py
  src/pymovements/utils/aois.py
  tests/files/potec_word_aoi_b0.tsv
  tests/unit/events/event_aoi_mapping_test.py
  tests/unit/gaze/gaze_aoi_mapping_test.py
Labels: enhancement

#786 feat!: resume archive extraction by skipping existing files
  src/pymovements/dataset/dataset.py
  src/pymovements/dataset/dataset_download.py
  src/pymovements/utils/archives.py
  tests/unit/dataset/dataset_download_test.py
  tests/unit/utils/archives_test.py
Labels: enhancement, breaking

#1012 chore: rename user agent to pymovements
  src/pymovements/utils/downloads.py
Labels: internal

#1008 feat: implement `Screen` as dataclass
  src/pymovements/gaze/experiment.py
  src/pymovements/gaze/gaze_dataframe.py
  src/pymovements/gaze/screen.py
  src/pymovements/utils/__init__.py
  src/pymovements/utils/decorators.py
Labels: enhancement

#1010 feat: improve `Experiment` class
  src/pymovements/dataset/dataset_definition.py
  src/pymovements/datasets/bsc.py
  src/pymovements/datasets/bsc2.py
  src/pymovements/datasets/codecomprehension.py
  src/pymovements/datasets/copco.py
  src/pymovements/datasets/daemons.py
  src/pymovements/datasets/didec.py
  src/pymovements/datasets/emtec.py
  src/pymovements/datasets/fakenews.py
  src/pymovements/datasets/gaze_graph.py
  src/pymovements/datasets/gaze_on_faces.py
  src/pymovements/datasets/gazebase.py
  src/pymovements/datasets/gazebasevr.py
  src/pymovements/datasets/hbn.py
  src/pymovements/datasets/interead.py
  src/pymovements/datasets/judo1000.py
  src/pymovements/datasets/potec.py
  src/pymovements/datasets/provo.py
  src/pymovements/datasets/sb_sat.py
  src/pymovements/datasets/toy_dataset.py
  src/pymovements/datasets/toy_dataset_eyelink.py
  src/pymovements/gaze/experiment.py
  src/pymovements/gaze/gaze_dataframe.py
  src/pymovements/gaze/io.py
  tests/unit/dataset/dataset_files_test.py
  tests/unit/gaze/experiment_test.py
  tests/unit/gaze/gaze_dataframe_test.py
Labels: enhancement

#974 docs: update supported file formats in Dataset docstring (#974)
  src/pymovements/dataset/dataset.py
Labels: documentation

#1022 feat: add DatasetLibrary.names()
  src/pymovements/dataset/dataset_library.py
  tests/unit/dataset/dataset_library_test.py
Labels: enhancement

#1040 docs: Add metadata to public datasets table
  docs/source/bibliography.bib
  docs/source/datasets/example_datasets.csv
  docs/source/datasets/index.rst
  docs/source/datasets/public_datasets.csv
Labels: documentation

#1048 chore: Create issue template for adding new datasets
  .github/ISSUE_TEMPLATE/DATASET.md
Labels: internal

#1050 fix: deduplicate resource filenames in UCL dataset
  src/pymovements/datasets/ucl.py
  src/pymovements/datasets/ucl.yaml
Labels: fix, dataset

#1036 ci: add performance section to release-drafter
  .github/release-drafter.yml
Labels: internal

#1009 dataset: add mousecursor dataset by Pantanowitz et al.
  docs/source/bibliography.bib
  docs/source/datasets/public_datasets.csv
  src/pymovements/datasets/__init__.py
  src/pymovements/datasets/datasets.yaml
  src/pymovements/datasets/mousecursor.py
  src/pymovements/datasets/mousecursor.yaml
  src/pymovements/utils/downloads.py
  tests/unit/datasets/datasets_test.py
Labels: dataset

#1028 depr: deprecate `utils.archives` in favor of `Dataset.extract()`
  src/pymovements/dataset/_utils/_archives.py
  src/pymovements/dataset/dataset_download.py
  src/pymovements/utils/archives.py
  src/pymovements/utils/downloads.py
  src/pymovements/utils/parsing.py
  tests/unit/dataset/_utils/_archives_test.py
  tests/unit/utils/archives_test.py
Labels: deprecation

#1052 chore: simplify public datasets tests
  tests/unit/datasets/datasets_test.py
Labels: internal

#1049 ci: run integration tests for all datasets in library
  .github/workflows/datasets.yml
  tests/integration/download_dataset_test.py
Labels: internal

#1044 dataset: add potsdam binge pvt datasets
  docs/source/bibliography.bib
  docs/source/datasets/public_datasets.csv
  src/pymovements/datasets/__init__.py
  src/pymovements/datasets/datasets.yaml
  src/pymovements/datasets/potsdam_binge_remote_pvt.py
  src/pymovements/datasets/potsdam_binge_remote_pvt.yaml
  src/pymovements/datasets/potsdam_binge_wearable_pvt.py
  src/pymovements/datasets/potsdam_binge_wearable_pvt.yaml
  tests/files/potsdam_binge_pvt_example.csv
  tests/functional/dataset_processing_test.py
  tests/unit/datasets/datasets_test.py
Labels: dataset

#1058 feat: make `mirrors` optional for downloading datasets
  src/pymovements/dataset/dataset_download.py
  tests/unit/dataset/dataset_download_test.py
  tests/unit/dataset/dataset_library_test.py
  tests/unit/dataset/dataset_test.py
Labels: enhancement

#1065 ci: remove xfails for #475 as they pass
  tests/unit/gaze/transforms/pos2acc_test.py
  tests/unit/gaze/transforms/pos2vel_test.py
  tests/unit/gaze/transforms/savitzky_golay_test.py
Labels: internal

#1030 depr: deprecate `utils.downloads` in favor of `Dataset.download()`
  src/pymovements/dataset/_utils/_downloads.py
  src/pymovements/dataset/dataset_download.py
  src/pymovements/utils/downloads.py
  tests/unit/dataset/_utils/_downloads_test.py
  tests/unit/utils/downloads_test.py
Labels: deprecation

#1034 perf: resume archive extraction by default
  src/pymovements/dataset/_utils/_archives.py
  src/pymovements/dataset/_utils/_downloads.py
  src/pymovements/dataset/dataset.py
  src/pymovements/dataset/dataset_download.py
  src/pymovements/utils/archives.py
  tests/unit/dataset/dataset_download_test.py
Labels: performance

#1067 docs: add source button to sphinx docs
  docs/source/conf.py
Labels: documentation

#1063 chore: add pymovements version to download user agent
  src/pymovements/dataset/_utils/_downloads.py
Labels: internal

#1069 dataset: add trial_columns to ToyDatasetEyeLink
  src/pymovements/datasets/toy_dataset_eyelink.py
  src/pymovements/datasets/toy_dataset_eyelink.yaml
Labels: dataset

#1070 chore: refactor GazeDataFrame init
  src/pymovements/gaze/gaze_dataframe.py
Labels: internal
