Repository aeye-lab/pymovements, pull requests merged in 2025-08, with the labels that each got.

#1160 feat: add `ResourceDefinitions` and use it in `DatasetDefinition`
  src/pymovements/__init__.py
  src/pymovements/dataset/__init__.py
  src/pymovements/dataset/_utils/_resources.py
  src/pymovements/dataset/dataset_definition.py
  src/pymovements/dataset/dataset_download.py
  src/pymovements/dataset/resources.py
  src/pymovements/datasets/bsc.py
  src/pymovements/datasets/bsc2.py
  src/pymovements/datasets/chinese_reading.py
  src/pymovements/datasets/codecomprehension.py
  src/pymovements/datasets/colagaze.py
  src/pymovements/datasets/copco.py
  src/pymovements/datasets/daemons.py
  src/pymovements/datasets/didec.py
  src/pymovements/datasets/emtec.py
  src/pymovements/datasets/etdd70.py
  src/pymovements/datasets/fakenews.py
  src/pymovements/datasets/gaze4hate.py
  src/pymovements/datasets/gaze_graph.py
  src/pymovements/datasets/gaze_on_faces.py
  src/pymovements/datasets/gazebase.py
  src/pymovements/datasets/gazebasevr.py
  src/pymovements/datasets/hbn.py
  src/pymovements/datasets/iitb_hgc.py
  src/pymovements/datasets/interead.py
  src/pymovements/datasets/judo1000.py
  src/pymovements/datasets/mousecursor.py
  src/pymovements/datasets/onestop.py
  src/pymovements/datasets/potec.py
  src/pymovements/datasets/potsdam_binge_remote_pvt.py
  src/pymovements/datasets/potsdam_binge_wearable_pvt.py
  src/pymovements/datasets/provo.py
  src/pymovements/datasets/sb_sat.py
  src/pymovements/datasets/toy_dataset.py
  src/pymovements/datasets/toy_dataset_eyelink.py
  src/pymovements/datasets/ucl.py
  src/pymovements/gaze/experiment.py
  tests/unit/dataset/dataset_definition_test.py
  tests/unit/dataset/dataset_download_test.py
  tests/unit/dataset/resources_test.py
Labels: enhancement

#1196 feat: split by trial columns per default
  src/pymovements/events/frame.py
  src/pymovements/gaze/gaze_dataframe.py
  tests/unit/events/frame_test.py
  tests/unit/gaze/gaze_dataframe_test.py
Labels: enhancement

#1119 depr: deprecate GazeDataFrame in favor of Gaze
  src/pymovements/__init__.py
  src/pymovements/_utils/_deprecated.py
  src/pymovements/dataset/dataset.py
  src/pymovements/dataset/dataset_files.py
  src/pymovements/events/processing.py
  src/pymovements/gaze/__init__.py
  src/pymovements/gaze/experiment.py
  src/pymovements/gaze/gaze.py
  src/pymovements/gaze/gaze_dataframe.py
  src/pymovements/gaze/integration.py
  src/pymovements/gaze/io.py
  src/pymovements/gaze/screen.py
  src/pymovements/plotting/heatmap.py
  src/pymovements/plotting/scanpathplot.py
  src/pymovements/plotting/traceplot.py
  src/pymovements/plotting/tsplot.py
  tests/unit/dataset/dataset_test.py
  tests/unit/events/event_aoi_mapping_test.py
  tests/unit/events/processing_test.py
  tests/unit/gaze/apply_test.py
  tests/unit/gaze/detect_test.py
  tests/unit/gaze/gaze_aoi_mapping_test.py
  tests/unit/gaze/gaze_dataframe_test.py
  tests/unit/gaze/gaze_init_test.py
  tests/unit/gaze/gaze_test.py
  tests/unit/gaze/gaze_transform_test.py
  tests/unit/gaze/gaze_unnest_test.py
  tests/unit/gaze/integration_numpy_test.py
  tests/unit/gaze/integration_pandas_test.py
  tests/unit/gaze/io/csv_test.py
  tests/unit/gaze/io/ipc_test.py
  tests/unit/gaze/measure_test.py
  tests/unit/plotting/heatmap_test.py
Labels: deprecation

#1195 depr: deprecate `EventDataFrame.copy` in favor of `EventDataFrame.clone`
  src/pymovements/events/frame.py
  src/pymovements/gaze/gaze.py
  tests/unit/events/frame_test.py
Labels: deprecation

#1211 docs: add scanpathplot to online documentation
  docs/source/reference/plotting.rst
Labels: documentation

#1212 docs: add uv installation instructions
  docs/source/advanced-installation.rst
  docs/source/getting-started.rst
Labels: documentation

#1217 docs: add missing URL and DOI fields to bibliography.bib
  docs/source/bibliography.bib
Labels: documentation

#1239 docs: include from_file docstring in stimulus.rst
  docs/source/reference/stimulus.rst
Labels: documentation

#1243 feat: add fixations, saccades, blinks, microsaccades as class properties
  src/pymovements/events/events.py
  tests/unit/events/events_test.py
Labels: enhancement

#1252 docs: replacing three event related tutorials with one
  docs/source/tutorials/detecting-events.ipynb
  docs/source/tutorials/event-handling.ipynb
  docs/source/tutorials/event-properties.ipynb
  docs/source/tutorials/index.rst
  docs/source/tutorials/saving-loading-events.ipynb
Labels: documentation

#1245 chore: gitignore data directory
  .gitignore
Labels: internal

#1242 docs: switch to `rich_last_names` in citation formatting for correct decoding
  docs/source/conf.py
Labels: documentation

#1232 docs: add tutorial for creating synthetic data
  docs/source/tutorials/creating-synthetic-data.ipynb
  docs/source/tutorials/index.rst
Labels: documentation

#1258 docs: update dev dependency in getting started installation guide
  docs/source/getting-started.rst
Labels: documentation

#1253 feat: add Gaze.save() function
  src/pymovements/gaze/experiment.py
  src/pymovements/gaze/gaze.py
  tests/unit/gaze/gaze_test.py
Labels: enhancement

#1256 depr: deprecate scanpathplot events argument
  src/pymovements/plotting/scanpathplot.py
  src/pymovements/plotting/traceplot.py
  tests/unit/plotting/scanpathplot_test.py
Labels: deprecation

#1257 feat!: Add axes in- and output to plotting functions
  src/pymovements/plotting/_matplotlib.py
  src/pymovements/plotting/heatmap.py
  src/pymovements/plotting/main_sequence_plot.py
  src/pymovements/plotting/scanpathplot.py
  src/pymovements/plotting/traceplot.py
  src/pymovements/plotting/tsplot.py
  src/pymovements/utils/plotting.py
  tests/unit/plotting/axes_closefig_api_test.py
  tests/unit/plotting/figure_utils_test.py
  tests/unit/plotting/main_sequence_plot_test.py
  tests/unit/plotting/tsplot_test.py
Labels: enhancement, breaking
