Repository aeye-lab/pymovements, pull requests merged in 2025-02, with the labels that each got.

#935 build: upgrade polars>=1.21
  pyproject.toml
  src/pymovements/gaze/transforms.py
Labels: build

#943 ci: use minor versions as upper bound in dependencies
  pyproject.toml
Labels: internal

#859 feat: split_gaze_data by column values
  src/pymovements/dataset/dataset.py
  src/pymovements/gaze/gaze_dataframe.py
  tests/unit/dataset/dataset_test.py
  tests/unit/gaze/gaze_dataframe_test.py
Labels: enhancement

#958 dataset: add BSCII
  docs/source/bibliography.bib
  src/pymovements/datasets/__init__.py
  src/pymovements/datasets/bsc2.py
  tests/unit/datasets/datasets_test.py
Labels: dataset

#959 dataset: add Provo corpus
  docs/source/bibliography.bib
  src/pymovements/datasets/__init__.py
  src/pymovements/datasets/provo.py
  tests/unit/datasets/datasets_test.py
Labels: dataset

#964 dataset: add UCL dataset
  docs/source/bibliography.bib
  src/pymovements/datasets/__init__.py
  src/pymovements/datasets/ucl.py
  tests/unit/datasets/datasets_test.py
Labels: dataset

#966 docs: improve datasets error message
  src/pymovements/dataset/dataset_download.py
  tests/unit/dataset/dataset_download_test.py
Labels: documentation

#963 fix: add missing fakenews perception dataset to datasets/__init__.py
  src/pymovements/datasets/__init__.py
Labels: bug, fix

#965 chore: remove unnecessary .frame from import
  src/pymovements/dataset/dataset.py
Labels: internal

#977 docs: change mail address to @python.org
  README.md
Labels: documentation

#979 docs: Add subscription link for mailing list
  README.md
Labels: documentation
